apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: ghcr.io/2023-4400-exp/4415-go-server-ci:b3f1ca11e0ac4ed365088f95a96317474e68f3a7
        name: go-server-ci
